// ===== Translations =====
const translations = {
    en: {
        'nav.homepage': 'Homepage',
        'nav.about': 'About Me',
        'nav.cv': 'CV',
        'nav.publications': 'Publications',
        'nav.teaching': 'Teaching',
        'nav.supervision': 'Supervision',
        'nav.recentWorks': 'Recent Works',
        'nav.contact': 'Contact',
        'hero.university': 'Hacettepe University',
        'section.about': 'About Me',
        'section.cv': 'CV',
        'section.publications': 'Publications',
        'publications.pdf': 'PDF',
        'publications.allPublications': 'All Publications',
        'section.teaching': 'Teaching',
        'section.supervision': 'Supervision & Recent Works',
        'section.contact': 'Contact',
        'about.paragraph1': 'I am a Professor at the Department of Mathematics of the Faculty of Science of the University of Hacettepe in Ankara, Türkiye. I have been the head of the department from 2021 to 2024. I was an Editor-in-Chief at Hacettepe Journal of Mathematics and Statistics from 01.08.2018 to 30.07.2021. I am a member of the editorial board of the International Electronic Journal of Algebra and the Istanbul Journal of Mathematics.',
        'about.paragraph2': 'My research interest lies in Ring and Module Theory, specifically:',
        'about.researchList': '<li>Lifting of some kind of elements, such as idempotents, regular and unit regular elements</li><li>Stable Range Condition</li>',
        'about.paragraph3': 'I supervised 2 PhD and 2 Master students. I have currently 1 master student.',
        'cv.education': 'Education',
        'cv.education.highSchool': 'High School: 1989, Şehit Mehmet Gönenç Lisesi, Bandırma',
        'cv.education.bachelor': 'Bachelor: 1989-1993, Hacettepe University, Department of Mathematics',
        'cv.education.master': 'Master: 1993-1995, Hacettepe University, Department of Mathematics',
        'cv.education.phd': 'PhD: 1995-1999, Hacettepe University, Department of Mathematics',
        'cv.education.phdAdvisor': 'Advisor: Prof. Dr. Abdullah Harmancı',
        'cv.education.phdThesis': 'Thesis Title: Characterizations of Some Rings by Small Modules and Decompositions of Modules',
        'cv.education.associate': 'Associate Professor: November 2002, Hacettepe University, Algebra and Number Theory',
        'cv.education.professor': 'Professor: April 2009, Hacettepe University, Algebra and Number Theory',
        'cv.areaOfInterest': 'Area of Interest',
        'cv.areaOfInterest.intro': 'Ring and Module Theory:',
        'cv.areaOfInterest.small': 'Small modules',
        'cv.areaOfInterest.zfunctor': 'Z*(.) Functor',
        'cv.areaOfInterest.torsion': 'Torsion theories (co)generated by certain classes of modules',
        'cv.areaOfInterest.vrings': 'V-rings (rings in which every simple module is injective)',
        'cv.areaOfInterest.gvrings': 'GV-rings (rings in which every simple singular module is injective)',
        'cv.areaOfInterest.semiregular': 'Semiregular rings and modules',
        'cv.areaOfInterest.semiperfect': 'Semiperfect rings and modules',
        'cv.areaOfInterest.perfect': 'Perfect rings and modules',
        'cv.areaOfInterest.harada': 'Harada rings and modules',
        'cv.areaOfInterest.qf': 'Quasi-Frobenious (QF) rings',
        'cv.areaOfInterest.clean': 'Clean Rings',
        'cv.areaOfInterest.stable': 'Stable Range',
        'cv.citations': 'Citations (Books)',
        'cv.citations.book1': 'J. Clark, C. Lomp, N. Vanaja, R. Wisbauer, Lifting Modules, Supplements and Projectivity in Module Theory, Birkhäuser Basel, 2006. (Ref: [7], [277], [278], [279])',
        'cv.citations.book2': 'A. Tuganbaev, Rings Close to Regular, Kluwer Academic Publishers, 2002. (Ref: [312])',
        'cv.conferencesAbroad': 'Conferences Abroad',
        'cv.conferencesAbroad.1': '12-17 January 1998, Murcia University, Spain "Euroconference Interactions Between Ring Theory and Representations of Algebras" (TÜBİTAK BDP Supported).',
        'cv.conferencesAbroad.2': 'January 1998 - June 1998, Glasgow University, England (TÜBİTAK BDP Supported).',
        'cv.conferencesAbroad.3': '25-28 March 1999, Ohio University, USA. "International Conference on Algebra and Its Applications" (TÜBİTAK supported).',
        'cv.conferencesAbroad.4': '14-18 August 2000, Ovidius University, Constanta, Romania "The Euroconference on Rings, Modules and Representations".',
        'cv.conferencesAbroad.5': '8-10 September 2006, Porto University, Porto, Portugal, "International Conference on Modules and Comodules" dedicated to Robert Wisbauer.',
        'cv.conferencesAbroad.6': '10-15 September 2007, "The Fifth China-Japan-Korea International Symposium on Ring Theory", Tokyo, Japan.',
        'cv.conferencesAbroad.7': '16-19 September 2008, "International Conference on Rings and Modules in honour of Patrick F. Smith\'s 65th Birthday", Lisbon, Portugal.',
        'cv.conferencesAbroad.8': '29 June-2 July 2009, "Noncommutative Rings and Their Applications", Lens, France.',
        'cv.conferencesAbroad.9': '25-27 May 2012, The 31st Ohio State-Denison Mathematics Conference, Columbus, Ohio.',
        'cv.conferencesAbroad.10': '3-7 June 2013, Recent Trends in Rings and Algebras, Murcia, Spain.',
        'cv.conferencesAbroad.11': '14-20 July 2013, Classical Aspects on Ring Theory and Module Theory, Bedlewo, Poland.',
        'cv.conferencesAbroad.12': '8-11 June 2015, Noncommutative rings and their applications, IV, Lens, France.',
        'cv.conferencesAbroad.13': '18-25 May 2018, Padova University, Padova, Italy.',
        'cv.conferencesHome': 'Conferences at Home',
        'cv.conferencesHome.1': '19-23 May 1999, Antalya Algebra Days I, TÜBİTAK Mathematics Working Group, Antalya.',
        'cv.conferencesHome.2': '17-21 May 2000, Antalya Algebra Days II, Antalya.',
        'cv.conferencesHome.3': '6-9 September 2000, XIII. National Mathematics Symposium, İstanbul.',
        'cv.conferencesHome.4': '15-20 May 2001, Antalya Algebra Days III, Antalya.',
        'cv.conferencesHome.5': '22-26 May 2002, Antalya Algebra Days IV, Antalya.',
        'cv.conferencesHome.6': '28 May-1 June 2003, Antalya Algebra Days V, Antalya.',
        'cv.conferencesHome.7': '23-26 August 2004, XVII. National Mathematics Symposium, Abant İzzet Baysal University, Bolu.',
        'cv.conferencesHome.8': '17-20 May 2005, Antalya Algebra Days VII, Antalya.',
        'cv.conferencesHome.9': '5-8 September 2005, XVIII. National Mathematics Symposium, İstanbul Kültür University.',
        'cv.conferencesHome.10': '17-21 May 2006, Antalya Algebra Days VIII, Antalya.',
        'cv.conferencesHome.11': '28 May - 1 June 2008, Antalya Algebra Days X, Antalya.',
        'cv.conferencesHome.12': '18-22 August 2008, Rings and Modules, Hacettepe University, Ankara.',
        'cv.conferencesHome.13': '20-24 May 2009, Antalya Algebra Days XI, Antalya.',
        'cv.conferencesHome.14': '19-22 May 2010, Antalya Algebra Days XII, Antalya.',
        'cv.conferencesHome.15': '3-4 June 2010, 5th Ankara Mathematics Days, TOBB University of Economics and Technology, Ankara.',
        'cv.conferencesHome.16': '2-3 June 2011, 6th Ankara Mathematics Days, Hacettepe University, Ankara.',
        'cv.conferencesHome.17': '20-23 July 2011, The 24th International Conference of Jungjeon Mathematical Society, Selçuk University, Konya.',
        'cv.conferencesHome.18': '31 May-1 June 2012, 7th Ankara Mathematics Days, Bilkent University, Ankara.',
        'cv.conferencesHome.19': '11-15 June 2012, Workshop on Ring Theory, Karabük University, Karabük.',
        'cv.conferencesHome.20': '23-25 May 2013, 12th Mathematics Symposium: Mathematics in Society, Hacettepe University.',
        'cv.conferencesHome.21': '24-28 June 2013, Ring and Module Workshop, İzmir Institute of Technology, Urla, İzmir.',
        'cv.conferencesHome.22': '12-15 August 2013, International Conference on Algebra, Balıkesir University, Burhaniye, Balıkesir.',
        'cv.conferencesHome.23': '1-5 June 2015, 4th Ring and Module Workshop, Hacettepe University, Ankara.',
        'cv.conferencesHome.24': '22-23 April 2016, 4th Cemal Koç Algebra Days, METU, Ankara.',
        'cv.conferencesHome.25': '30 May-3 June 2016, 5th Ring and Module Workshop, Hacettepe University, Ankara.',
        'cv.conferencesHome.26': '3-7 July 2017, 6th Ring and Module Workshop, Dokuz Eylül University, İzmir. Invited Speaker.',
        'cv.conferencesHome.27': '29 January-2 February 2018, Algebra Workshop, Afyon Kocatepe University, Afyon.',
        'cv.conferencesHome.28': '20-24 June 2018, New Trends in Rings and Modules, Gebze Technical University, Gebze.',
        'cv.seminars': 'Seminars',
        'cv.seminars.1': '28 February 2008, Bolu Abant İzzet Baysal University, Bolu, Türkiye',
        'cv.seminars.2': '26 March 2010, Bilkent University, Ankara, Türkiye',
        'cv.seminars.3': '19 October 2011, Hacettepe University, Ankara, Türkiye',
        'cv.seminars.4': '24 May 2018, Padova University, Padova, Italy',
        'cv.committees': 'Committees',
        'cv.committees.1': '12th Mathematics Symposium, Hacettepe University, Sıhhıye Campus, Cultural Center, 23-25 May 2013, Ankara. (Scientific Committee)',
        'cv.committees.2': 'International Conference on Algebra in Honour of Patrick Smith and John Clark\'s 70th Birthdays, Balıkesir, Türkiye, 12-15 August 2013. (Organizing Committee and Scientific Committee)',
        'cv.supervision': 'Supervision',
        'cv.supervision.master': 'Master\'s:',
        'cv.supervision.master1': 'Pınar Aydoğdu, "Generalization of Semiregular and Semiperfect Rings", 2004-2006.',
        'cv.supervision.master2': 'Meltem Altun, "Some Ring and Module Structures Defined by Morphisms", 2010-2013.',
        'cv.supervision.phd': 'PhD:',
        'cv.supervision.phd1': 'Pınar Aydoğdu, "A Study on Perfect and Regular Rings", 2007-2011.',
        'cv.supervision.phd2': 'Meltem Altun, "A Study on Direct Summand Submodules in Noncommutative Rings", 2013-2018.',
        'cv.editorial': 'Editorial',
        'cv.editorial.1': 'International Electronic Journal of Algebra (2007-)',
        'cv.editorial.2': 'International Journal of Mathematics and Mathematical Sciences (Guest Editor)',
        'cv.editorial.3': 'Hacettepe Journal of Mathematics and Statistics (01.08.2018-30.07.2021) (Editor-in-Chief)',
        'cv.editorial.4': 'Istanbul University Science Faculty The Journal of Mathematics, Physics and Astronomy (12.2018-) (Field Editor)',
        'cv.refereeing': 'Refereeing',
        'cv.refereeing.journals': 'Turkish J. Math., Hacettepe J. Math. Stat., Bull. Korean Math. Soc, Algebra Colloquium, Bull. Malaysian Math. Soc., Asian-European J. Math., Bull. Iranian Math. Soc., J. Algebra and its Applications',
        'cv.officialDuties': 'Administrative Duties',
        'cv.officialDuties.1': 'Head of Algebra and Number Theory Department (2009-2018)',
        'cv.officialDuties.2': 'Head of Mathematics Department (08.06.2021-)',
        'teaching.coursesTaught': 'Courses Taught',
        'teaching.undergraduate': 'Undergraduate:',
        'teaching.graduate': 'Graduate - PhD:',
        'teaching.serviceCourses': 'Service Courses:',
        'supervision.title': 'Supervision',
        'supervision.example1': 'Thesis Title Example 1 - Student Name - Degree Level - Year',
        'supervision.example2': 'Thesis Title Example 2 - Student Name - Degree Level - Year',
        'supervision.example3': 'Thesis Title Example 3 - Student Name - Degree Level - Year',
        'recentWorks.title': 'Recent Works',
        'recentWorks.example1': 'Recent Work Title 1 - Description of recent work will be added here...',
        'recentWorks.example2': 'Recent Work Title 2 - Description of recent work will be added here...',
        'recentWorks.example3': 'Recent Work Title 3 - Description of recent work will be added here...',
        'contact.firstName': 'First Name',
        'contact.lastName': 'Last Name',
        'contact.emailLabelForm': 'Email',
        'contact.message': 'Message',
        'contact.submit': 'Send',
        'contact.university': 'Hacettepe University',
        'contact.facultyLabel': 'Faculty of Science',
        'contact.departmentLabel': 'Department of Mathematics',
        'contact.addressLabel': 'Address:',
        'contact.address': 'Hacettepe Üniversitesi Beytepe Yerleşkesi Matematik Fakültesi',
        'contact.phoneLabel': 'Phone:',
        'contact.phone': '0 312 297 78 50/133',
        'contact.faxLabel': 'Fax:',
        'contact.fax': '0 312 299 20 17',
        'contact.emailLabel': 'Email:',
        'contact.email': 'ozcan@hacettepe.edu.tr',
        'footer.name': 'Prof. Dr. Ayşe Çiğdem Özcan',
        'footer.university': 'Hacettepe University',
        'footer.rights': 'All rights reserved.',
        'form.success': 'Your message has been sent successfully! (This is a demo form, there is no real backend connection.)',
        'form.error': 'Please fill in all fields.',
        'form.error.firstName': 'First name is required',
        'form.error.lastName': 'Last name is required',
        'form.error.email': 'Email is required',
        'form.error.emailInvalid': 'Please enter a valid email address',
        'form.error.message': 'Message is required',
        'form.error.messageShort': 'Message must be at least 10 characters',
        'form.error.mailClient': 'Unable to open mail client. Please send an email manually.'
    },
    tr: {
        'nav.homepage': 'Ana Sayfa',
        'nav.about': 'Hakkımda',
        'nav.cv': 'Özgeçmiş',
        'nav.publications': 'Yayınlar',
        'nav.teaching': 'Dersler',
        'nav.supervision': 'Danışmanlık',
        'nav.recentWorks': 'Son Çalışmalar',
        'nav.contact': 'İletişim',
        'hero.university': 'Hacettepe Üniversitesi',
        'section.about': 'Hakkımda',
        'section.cv': 'Özgeçmiş',
        'section.publications': 'Yayınlar',
        'publications.pdf': 'PDF',
        'publications.allPublications': 'Tüm Yayınlar',
        'section.teaching': 'Dersler',
        'section.supervision': 'Danışmanlık ve Son Çalışmalar',
        'section.contact': 'İletişim',
        'about.paragraph1': 'Ankara, Türkiye\'deki Hacettepe Üniversitesi Fen Fakültesi Matematik Bölümü\'nde Profesörüm. 2021\'den 2024\'e kadar bölüm başkanlığı yaptım. 01.08.2018 - 30.07.2021 tarihleri arasında Hacettepe Journal of Mathematics and Statistics dergisinde Editör-in-Chief olarak görev yaptım. International Electronic Journal of Algebra ve Istanbul Journal of Mathematics dergilerinin yayın kurulu üyesiyim.',
        'about.paragraph2': 'Araştırma ilgi alanım Halka ve Modül Teorisi\'dir, özellikle:',
        'about.researchList': '<li>Bazı elemanların kaldırılması, örneğin idempotentler, düzenli ve birim düzenli elemanlar</li><li>Kararlı Aralık Koşulu</li>',
        'about.paragraph3': '2 doktora ve 2 yüksek lisans öğrencisine danışmanlık yaptım. Şu anda 1 yüksek lisans öğrencim var.',
        'cv.education': 'Eğitim',
        'cv.education.highSchool': 'Lise: 1989, Şehit Mehmet Gönenç Lisesi, Bandırma',
        'cv.education.bachelor': 'Lisans: 1989-1993, Hacettepe Üniversitesi, Matematik Bölümü',
        'cv.education.master': 'Yüksek Lisans: 1993-1995, Hacettepe Üniversitesi, Matematik Bölümü',
        'cv.education.phd': 'Doktora: 1995-1999, Hacettepe Üniversitesi, Matematik Bölümü',
        'cv.education.phdAdvisor': 'Danışman: Prof. Dr. Abdullah Harmancı',
        'cv.education.phdThesis': 'Tez Başlığı: Atık Modüller Yardımıyla Bazı Halkaların Karakterizasyonları ve Modüllerin Parçalanışları',
        'cv.education.associate': 'Doçent: Kasım 2002, Hacettepe Üniversitesi, Cebir ve Sayılar Teorisi Anabilim Dalı',
        'cv.education.professor': 'Profesör: Nisan 2009, Hacettepe Üniversitesi, Cebir ve Sayılar Teorisi Anabilim Dalı',
        'cv.areaOfInterest': 'Akademik İlgi Alanları',
        'cv.areaOfInterest.intro': 'Halka ve modül teorileri:',
        'cv.areaOfInterest.small': 'Atık (small) modüller',
        'cv.areaOfInterest.zfunctor': 'Z*(.) funktoru',
        'cv.areaOfInterest.torsion': 'Bazı modül sınıflarının (eş-)üretmiş olduğu burulma (torsion) teorileri',
        'cv.areaOfInterest.vrings': 'V-halkalar (her basit modülü injektif olan halkalar)',
        'cv.areaOfInterest.gvrings': 'GV-halkalar (her basit tekil (singular) modülü injektif olan halkalar)',
        'cv.areaOfInterest.semiregular': 'Yarı düzenli (semiregular) halkalar ve modüller',
        'cv.areaOfInterest.semiperfect': 'Yarı tam (semiperfect) halkalar ve modüller',
        'cv.areaOfInterest.perfect': 'Tam (perfect) halkalar ve modüller',
        'cv.areaOfInterest.harada': 'Harada halkalar ve modüller',
        'cv.areaOfInterest.qf': 'Quasi-Frobenious (QF) halkalar',
        'cv.areaOfInterest.clean': 'Temiz Halkalar',
        'cv.areaOfInterest.stable': 'Stable Range',
        'cv.citations': 'Atıflar (Kitap)',
        'cv.citations.book1': 'J. Clark, C. Lomp, N. Vanaja, R. Wisbauer, Lifting Modules, Supplements and Projectivity in Module Theory, Birkhäuser Basel, 2006. (Ref: [7], [277], [278], [279])',
        'cv.citations.book2': 'A. Tuganbaev, Rings Close to Regular, Kluwer Academic Publishers, 2002. (Ref: [312])',
        'cv.conferencesAbroad': 'Yurt Dışı Görevlendirmeler',
        'cv.conferencesAbroad.1': '12-17 Ocak 1998, Murcia Üniversitesi, İspanya "Euroconference Interactions Between Ring Theory and Representations of Algebras" (TÜBİTAK BDP Destekli).',
        'cv.conferencesAbroad.2': 'Ocak 1998 - Haziran 1998, Glasgow Üniversitesi, İngiltere (TÜBİTAK BDP Destekli).',
        'cv.conferencesAbroad.3': '25-28 Mart 1999, Ohio Üniversitesi, ABD. "International Conference on Algebra and Its Applications" Bildirili. (TÜBİTAK destekli)',
        'cv.conferencesAbroad.4': '14-18 Ağustos 2000, Ovidius Üniversitesi, Constanta, Romanya "The Euroconference on Rings, Modules and Representations" Bildirili.',
        'cv.conferencesAbroad.5': '8-10 Eylül 2006, Porto Üniversitesi, Porto, Portekiz, "International Conference on Modules and Comodules" dedicated to Robert Wisbauer. Bildirili.',
        'cv.conferencesAbroad.6': '10-15 Eylül 2007, "The Fifth China-Japan-Korea International Symposium on Ring Theory", Tokyo, Japonya. Bildirili.',
        'cv.conferencesAbroad.7': '16-19 Eylül 2008, "International Conference on Rings and Modules in honour of Patrick F. Smith\'s 65th Birthday", Lizbon, Portekiz.',
        'cv.conferencesAbroad.8': '29 Haziran-2 Temmuz 2009, "Noncommutative Rings and Their Applications", Lens, Fransa. Bildirili.',
        'cv.conferencesAbroad.9': '25-27 Mayıs 2012, The 31st Ohio State-Denison Mathematics Conference, Columbus, Ohio. Bildirili.',
        'cv.conferencesAbroad.10': '3-7 Haziran 2013, Recent Trends in Rings and Algebras, Murcia, Spain.',
        'cv.conferencesAbroad.11': '14-20 Temmuz 2013, Classical Aspects on Ring Theory and Module Theory, Bedlewo, Polonya. Bildirili.',
        'cv.conferencesAbroad.12': '8-11 Haziran 2015, Noncommutative rings and their applications, IV, Lens, Fransa.',
        'cv.conferencesAbroad.13': '18-25 Mayıs 2018, Padova Üniversitesi, Padova, Italya.',
        'cv.conferencesHome': 'Yurt İçi Toplantılar',
        'cv.conferencesHome.1': '19-23 Mayıs 1999, Antalya Cebir Günleri I, Tübitak Matematik Çalışma Grubu, Antalya. Bildirili.',
        'cv.conferencesHome.2': '17-21 Mayıs 2000, Antalya Cebir Günleri II, Antalya. Bildirili.',
        'cv.conferencesHome.3': '6-9 Eylül 2000, XIII. Ulusal Matematik Sempozyumu, İstanbul.',
        'cv.conferencesHome.4': '15-20 Mayıs 2001, Antalya Cebir Günleri III, Antalya. Bildirili.',
        'cv.conferencesHome.5': '22-26 Mayıs 2002, Antalya Cebir Günleri IV, Antalya.',
        'cv.conferencesHome.6': '28 Mayıs-1 Haziran 2003, Antalya Cebir Günleri V, Antalya. Bildirili.',
        'cv.conferencesHome.7': '23-26 Ağustos 2004, XVII. Ulusal Matematik Sempozyumu, Abant İzzet Baysal Üniversitesi, Bolu. Bildirili.',
        'cv.conferencesHome.8': '17-20 Mayıs 2005, Antalya Cebir Günleri VII, Antalya. Bildirili.',
        'cv.conferencesHome.9': '5-8 Eylül 2005, XVIII. Ulusal Matematik Sempozyumu, İstanbul Kültür Üniversitesi.',
        'cv.conferencesHome.10': '17-21 Mayıs 2006, Antalya Cebir Günleri VIII, Antalya.',
        'cv.conferencesHome.11': '28 Mayıs - 1 Haziran 2008, Antalya Cebir Günleri X, Antalya. Bildirili.',
        'cv.conferencesHome.12': '18-22 Ağustos 2008, Rings and Modules, Hacettepe Üniversitesi, Ankara.',
        'cv.conferencesHome.13': '20-24 Mayıs 2009, Antalya Cebir Günleri XI, Antalya.',
        'cv.conferencesHome.14': '19-22 Mayıs 2010, Antalya Cebir Günleri XII, Antalya.',
        'cv.conferencesHome.15': '3-4 Haziran 2010, 5. Ankara Matematik Günleri, TOBB Ekonomi ve Teknoloji Üniversitesi, Ankara.',
        'cv.conferencesHome.16': '2-3 Haziran 2011, 6. Ankara Matematik Günleri, Hacettepe Üniversitesi, Ankara.',
        'cv.conferencesHome.17': '20-23 Temmuz 2011, The 24th International Conference of Jungjeon Mathematical Society, Selçuk Üniversitesi, Konya. Bildirili.',
        'cv.conferencesHome.18': '31 Mayıs-1 Haziran 2012, 7. Ankara Matematik Günleri, Bilkent Üniversitesi, Ankara.',
        'cv.conferencesHome.19': '11-15 Haziran 2012, Workshop on Ring Theory, Karabük Üniversitesi, Karabük. Bildirili.',
        'cv.conferencesHome.20': '23-25 Mayıs 2013, 12. Matematik Sempozyumu: Toplumda Matematik, Hacettepe Üniversitesi.',
        'cv.conferencesHome.21': '24-28 Haziran 2013, Halka ve Modül Çalıştayı, İzmir Yüksek Teknoloji Enstitüsü, Urla, İzmir.',
        'cv.conferencesHome.22': '12-15 Ağustos 2013, International Conference on Algebra, Balıkesir Üniversitesi, Burhaniye, Balıkesir.',
        'cv.conferencesHome.23': '1-5 Haziran 2015, 4. Halka ve Modül Çalıştayı, Hacettepe Ü. Ankara.',
        'cv.conferencesHome.24': '22-23 Nisan 2016, 4th Cemal Koç Algebra Days, METU, Ankara.',
        'cv.conferencesHome.25': '30 Mayıs-3 Haziran 2016, 5. Halka ve Modül Çalıştayı, Hacettepe Ü. Ankara.',
        'cv.conferencesHome.26': '3-7 Temmuz 2017, 6. Halka ve Modül Çalıştayı, Dokuz Eylül Üniversitesi, İzmir. Davetli Konuşmacı.',
        'cv.conferencesHome.27': '29 Ocak-2 Şubat 2018, Cebir Çalıştayı, Afyon Kocatepe Üniversitesi, Afyon.',
        'cv.conferencesHome.28': '20-24 Haziran 2018, New Trends in Rings and Modules, Gebze Teknik Üniversitesi, Gebze.',
        'cv.seminars': 'Seminerler',
        'cv.seminars.1': '28 Şubat 2008, Bolu Abant İzzet Baysal Üniversitesi, Bolu, Türkiye',
        'cv.seminars.2': '26 Mart 2010, Bilkent Üniversitesi, Ankara, Türkiye',
        'cv.seminars.3': '19 Ekim 2011, Hacettepe Üniversitesi, Ankara, Türkiye',
        'cv.seminars.4': '24 Mayıs 2018, Padova Üniversitesi, Padova, İtalya',
        'cv.committees': 'Komiteler',
        'cv.committees.1': '12. Matematik Sempozyumu, Hacettepe Üniversitesi, Sıhhıye Yerleşkesi, Kültür Merkezi, 23-25 Mayıs 2013, Ankara. (Bilim Komitesi)',
        'cv.committees.2': 'International Conference on Algebra in Honour of Patrick Smith and John Clark\'s 70th Birthdays, Balıkesir, Türkiye, 12-15 Ağustos 2013. (Organizasyon Komitesi ve Bilim Komitesi)',
        'cv.supervision': 'Danışmanlık',
        'cv.supervision.master': 'Yüksek Lisans:',
        'cv.supervision.master1': 'Pınar Aydoğdu, "Yarıdüzenli ve Yarıtam Halkaların Genellemesi", 2004-2006.',
        'cv.supervision.master2': 'Meltem Altun, "Morfizmalar Yardımıyla Tanımlanan Bazı Halka ve Modül Yapıları", 2010-2013.',
        'cv.supervision.phd': 'Doktora:',
        'cv.supervision.phd1': 'Pınar Aydoğdu, "Tam ve Düzenli Halkalar Üzerine bir Çalışma", 2007-2011.',
        'cv.supervision.phd2': 'Meltem Altun, "Değişmeli Olmayan Halkalarda Dik Toplanan Alt Modüller Üzerine Bir Çalışma", 2013-2018',
        'cv.editorial': 'Editörlük',
        'cv.editorial.1': 'International Electronic Journal of Algebra (2007-)',
        'cv.editorial.2': 'International Journal of Mathematics and Mathematical Sciences (Misafir Editör)',
        'cv.editorial.3': 'Hacettepe Journal of Mathematics and Statistics (01.08.2018-30.07.2021) (Baş Editör)',
        'cv.editorial.4': 'Istanbul University Science Faculty The Journal of Mathematics, Physics and Astronomy (12.2018-) (Alan Editörü)',
        'cv.refereeing': 'Hakemlik',
        'cv.refereeing.journals': 'Turkish J. Math., Hacettepe J. Math. Stat., Bull. Korean Math. Soc, Algebra Colloquium, Bull. Malaysian Math. Soc., Asian-European J. Math., Bull. Iranian Math. Soc., J. Algebra and its Applications',
        'cv.officialDuties': 'İdari Görevler',
        'cv.officialDuties.1': 'Cebir ve Sayılar Teorisi Anabilim Dalı Başkanlığı (2009-2018)',
        'cv.officialDuties.2': 'Matematik Bölüm Başkanlığı (08.06.2021-)',
        'teaching.coursesTaught': 'Okutulmuş Olan Dersler',
        'teaching.undergraduate': 'Lisans:',
        'teaching.graduate': 'Yüksek Lisans - Doktora:',
        'teaching.serviceCourses': 'Servis Dersleri:',
        'supervision.title': 'Danışmanlık',
        'supervision.example1': 'Tez Başlığı Örneği 1 - Öğrenci Adı - Derece Seviyesi - Yıl',
        'supervision.example2': 'Tez Başlığı Örneği 2 - Öğrenci Adı - Derece Seviyesi - Yıl',
        'supervision.example3': 'Tez Başlığı Örneği 3 - Öğrenci Adı - Derece Seviyesi - Yıl',
        'recentWorks.title': 'Son Çalışmalar',
        'recentWorks.example1': 'Son Çalışma Başlığı 1 - Son çalışmanın açıklaması buraya eklenecek...',
        'recentWorks.example2': 'Son Çalışma Başlığı 2 - Son çalışmanın açıklaması buraya eklenecek...',
        'recentWorks.example3': 'Son Çalışma Başlığı 3 - Son çalışmanın açıklaması buraya eklenecek...',
        'contact.firstName': 'Ad',
        'contact.lastName': 'Soyad',
        'contact.emailLabelForm': 'E-posta',
        'contact.message': 'Mesaj',
        'contact.submit': 'Gönder',
        'contact.university': 'Hacettepe Üniversitesi',
        'contact.facultyLabel': 'Fen Fakültesi',
        'contact.departmentLabel': 'Matematik Bölümü',
        'contact.addressLabel': 'Adres:',
        'contact.address': 'Hacettepe Üniversitesi Beytepe Yerleşkesi Matematik Fakültesi',
        'contact.phoneLabel': 'Tel:',
        'contact.phone': '0 312 297 78 50/133',
        'contact.faxLabel': 'Faks:',
        'contact.fax': '0 312 299 20 17',
        'contact.emailLabel': 'E-posta:',
        'contact.email': 'ozcan@hacettepe.edu.tr',
        'footer.name': 'Prof. Dr. Ayşe Çiğdem Özcan',
        'footer.university': 'Hacettepe Üniversitesi',
        'footer.rights': 'Tüm hakları saklıdır.',
        'form.success': 'Mesajınız başarıyla gönderildi! (Bu bir demo formdur, gerçek bir backend bağlantısı yoktur.)',
        'form.error': 'Lütfen tüm alanları doldurun.',
        'form.error.firstName': 'Ad gereklidir',
        'form.error.lastName': 'Soyad gereklidir',
        'form.error.email': 'E-posta gereklidir',
        'form.error.emailInvalid': 'Lütfen geçerli bir e-posta adresi girin',
        'form.error.message': 'Mesaj gereklidir',
        'form.error.messageShort': 'Mesaj en az 10 karakter olmalıdır',
        'form.error.mailClient': 'E-posta istemcisi açılamadı. Lütfen manuel olarak e-posta gönderin.'
    }
};

// Current language (default: English)
let currentLang = 'en';

// ===== Language Switching =====
function switchLanguage(lang) {
    currentLang = lang;
    document.documentElement.lang = lang;
    
    // Store original HTML content for all elements with data-i18n before first translation
    // This allows HTML content to be preserved and restored when needed
    document.querySelectorAll('[data-i18n]').forEach(element => {
        if (!element.dataset.originalContent) {
            // Store original HTML content (either textContent or innerHTML depending on element type)
            if (element.tagName === 'UL' || element.tagName === 'OL' || element.tagName === 'P' || element.tagName === 'DIV') {
                element.dataset.originalContent = element.innerHTML;
            } else {
                element.dataset.originalContent = element.textContent || element.innerHTML;
            }
        }
    });
    
    // Update all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        
        // Check if element has original HTML content that should be preserved
        const hasOriginalContent = element.dataset.originalContent && element.dataset.originalContent.trim() !== '';
        
        // Apply translation only if available and user explicitly wants translation
        // Otherwise, always use HTML content (which is the source of truth)
        if (translations[lang] && translations[lang][key]) {
            // Special handling for email links
            if (element.tagName === 'A' && (key === 'contact.email' || element.id === 'contactEmailLink')) {
                const email = translations[lang]['contact.email'];
                element.textContent = email;
                element.href = 'mailto:' + email;
            } 
            // Special handling for education list items with labels
            else if (element.tagName === 'LI' && (key.startsWith('cv.education.highSchool') || key.startsWith('cv.education.bachelor') || key.startsWith('cv.education.master') || key.startsWith('cv.education.phd') || key.startsWith('cv.education.associate') || key.startsWith('cv.education.professor'))) {
                const translation = translations[lang][key];
                const parts = translation.split(':');
                if (parts.length > 1) {
                    element.innerHTML = '<span class="cv-label">' + parts[0] + ':</span> ' + parts.slice(1).join(':');
                } else {
                    element.innerHTML = translation;
                }
            }
            // For lists (UL, OL), only apply translation if it exists and is not empty
            // Otherwise keep HTML content
            else if (element.tagName === 'UL' || element.tagName === 'OL') {
                const translation = translations[lang][key];
                if (translation && translation.trim() !== '') {
                    element.innerHTML = translation;
                } else if (hasOriginalContent) {
                    // Restore original HTML content if translation is empty
                    element.innerHTML = element.dataset.originalContent;
                }
            }
            // For other elements, apply translation
            else if (element.tagName === 'STRONG') {
                element.textContent = translations[lang][key];
            } else {
                element.textContent = translations[lang][key];
            }
        } else if (hasOriginalContent) {
            // No translation available, restore original HTML content
            if (element.tagName === 'UL' || element.tagName === 'OL' || element.tagName === 'P' || element.tagName === 'DIV') {
                element.innerHTML = element.dataset.originalContent;
            } else {
                element.textContent = element.dataset.originalContent;
            }
        }
        // If no original content stored and no translation, HTML content (already in DOM) stays as is
    });
    
    // Update language toggle buttons
    document.querySelectorAll('.lang-btn').forEach(btn => {
        if (btn.getAttribute('data-lang') === lang) {
            btn.classList.add('active');
            btn.setAttribute('aria-pressed', 'true');
        } else {
            btn.classList.remove('active');
            btn.setAttribute('aria-pressed', 'false');
        }
    });
    
    // Store language preference
    localStorage.setItem('preferredLanguage', lang);
}

// Initialize language on page load
document.addEventListener('DOMContentLoaded', function() {
    // First, store all original HTML content before any translation
    // This ensures HTML content is always preserved and can be restored
    document.querySelectorAll('[data-i18n]').forEach(element => {
        // Always store current HTML content as the source of truth
        if (element.tagName === 'UL' || element.tagName === 'OL' || element.tagName === 'P' || element.tagName === 'DIV' || element.tagName === 'SPAN') {
            element.dataset.originalContent = element.innerHTML;
        } else {
            element.dataset.originalContent = element.textContent || element.innerHTML;
        }
    });
    
    // Check for saved language preference or default to English
    const savedLang = localStorage.getItem('preferredLanguage') || 'en';
    
    // Only apply translation if it's not the default language or if user explicitly changed language
    // For default language (en), keep HTML content as is
    if (savedLang !== 'en') {
        switchLanguage(savedLang);
    }
    // For English, HTML content stays as is (already in DOM)
    
    // Language toggle button event listeners
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.addEventListener('click', function() {
            const lang = this.getAttribute('data-lang');
            switchLanguage(lang);
        });
    });
});

// ===== Smooth Scroll Navigation =====
document.addEventListener('DOMContentLoaded', function() {
    // Get all navigation links
    const navLinks = document.querySelectorAll('.nav-link');
    
    navLinks.forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            
            const targetId = this.getAttribute('href');
            const targetSection = document.querySelector(targetId);
            
            if (targetSection) {
                const navHeight = document.querySelector('.navbar').offsetHeight;
                const targetPosition = targetSection.offsetTop - navHeight;
                
                window.scrollTo({
                    top: targetPosition,
                    behavior: 'smooth'
                });
                
                // Close mobile menu if open
                const navMenu = document.getElementById('nav-menu');
                navMenu.classList.remove('active');
            }
        });
    });
});

// ===== Mobile Menu Toggle =====
const hamburger = document.getElementById('hamburger');
const navMenu = document.getElementById('nav-menu');

if (hamburger && navMenu) {
    hamburger.addEventListener('click', function() {
        const isActive = navMenu.classList.toggle('active');
        hamburger.setAttribute('aria-expanded', isActive);
        
        // Animate hamburger icon
        const spans = hamburger.querySelectorAll('span');
        if (isActive) {
            spans[0].style.transform = 'rotate(45deg) translate(5px, 5px)';
            spans[1].style.opacity = '0';
            spans[2].style.transform = 'rotate(-45deg) translate(7px, -6px)';
        } else {
            spans[0].style.transform = 'none';
            spans[1].style.opacity = '1';
            spans[2].style.transform = 'none';
        }
    });

    // Close menu when clicking outside
    document.addEventListener('click', function(e) {
        if (!hamburger.contains(e.target) && !navMenu.contains(e.target) && navMenu.classList.contains('active')) {
            navMenu.classList.remove('active');
            hamburger.setAttribute('aria-expanded', 'false');
            const spans = hamburger.querySelectorAll('span');
            spans[0].style.transform = 'none';
            spans[1].style.opacity = '1';
            spans[2].style.transform = 'none';
        }
    });

    // Close menu on Escape key
    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && navMenu.classList.contains('active')) {
            navMenu.classList.remove('active');
            hamburger.setAttribute('aria-expanded', 'false');
            hamburger.focus();
            const spans = hamburger.querySelectorAll('span');
            spans[0].style.transform = 'none';
            spans[1].style.opacity = '1';
            spans[2].style.transform = 'none';
        }
    });
}

// ===== Image Slider =====
let currentSlide = 0;
let slides = [];
let dots = [];
let totalSlides = 0;
let slideInterval;

// Create dots dynamically based on slide count
function createDots() {
    const dotsContainer = document.querySelector('.slider-dots');
    if (!dotsContainer || slides.length === 0) return;
    
    // Clear existing dots
    dotsContainer.innerHTML = '';
    dots = [];
    
    // Create dots for each slide
    slides.forEach((slide, index) => {
        const dot = document.createElement('button');
        dot.className = 'dot';
        dot.setAttribute('data-slide', index);
        dot.setAttribute('aria-label', `Go to slide ${index + 1}`);
        dot.setAttribute('aria-selected', index === 0 ? 'true' : 'false');
        dot.setAttribute('role', 'tab');
        if (index === 0) {
            dot.classList.add('active');
        }
        
        // Add click event
        dot.addEventListener('click', function() {
            showSlide(index);
            restartAutoSlide();
        });
        
        // Keyboard navigation
        dot.addEventListener('keydown', function(e) {
            if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                showSlide(index);
                restartAutoSlide();
            }
        });
        
        dotsContainer.appendChild(dot);
        dots.push(dot);
    });
}

// Initialize slider
function initSlider() {
    // Get slides dynamically
    slides = Array.from(document.querySelectorAll('.slide'));
    totalSlides = slides.length;
    
    if (slides.length === 0) return;
    
    // If only one slide, hide controls and dots
    if (totalSlides === 1) {
        const controls = document.querySelector('.slider-controls');
        const dotsContainer = document.querySelector('.slider-dots');
        if (controls) controls.style.display = 'none';
        if (dotsContainer) dotsContainer.style.display = 'none';
        if (slides[0]) {
            slides[0].classList.add('active');
        }
        return;
    }
    
    // Create dots dynamically
    createDots();
    
    // Show first slide
    if (slides[0]) {
        slides[0].classList.add('active');
    }
    
    // Start auto-slide
    startAutoSlide();
}

// Show specific slide
function showSlide(index) {
    // Remove active class from all slides and dots
    slides.forEach(slide => slide.classList.remove('active'));
    dots.forEach((dot, i) => {
        dot.classList.remove('active');
        dot.setAttribute('aria-selected', 'false');
    });
    
    // Add active class to current slide and dot
    if (slides[index]) {
        slides[index].classList.add('active');
    }
    if (dots[index]) {
        dots[index].classList.add('active');
        dots[index].setAttribute('aria-selected', 'true');
    }
    
    currentSlide = index;
}

// Next slide
function nextSlide() {
    const next = (currentSlide + 1) % totalSlides;
    showSlide(next);
}

// Previous slide
function prevSlide() {
    const prev = (currentSlide - 1 + totalSlides) % totalSlides;
    showSlide(prev);
}

// Start auto-slide
function startAutoSlide() {
    slideInterval = setInterval(nextSlide, 4000); // Change slide every 4 seconds
}

// Stop auto-slide
function stopAutoSlide() {
    if (slideInterval) {
        clearInterval(slideInterval);
    }
}

// Restart auto-slide
function restartAutoSlide() {
    stopAutoSlide();
    startAutoSlide();
}

// Slider controls
const prevBtn = document.getElementById('prevBtn');
const nextBtn = document.getElementById('nextBtn');

if (prevBtn) {
    prevBtn.addEventListener('click', function() {
        prevSlide();
        restartAutoSlide();
    });
}

if (nextBtn) {
    nextBtn.addEventListener('click', function() {
        nextSlide();
        restartAutoSlide();
    });
}

// Dot navigation is now handled in createDots() function

// Pause slider on hover
const sliderContainer = document.querySelector('.slider-container');
if (sliderContainer) {
    sliderContainer.addEventListener('mouseenter', stopAutoSlide);
    sliderContainer.addEventListener('mouseleave', startAutoSlide);
}

// Initialize slider when page loads
document.addEventListener('DOMContentLoaded', function() {
    initSlider();
});

// ===== Scroll to Top Button =====
const scrollTopBtn = document.getElementById('scrollTop');

window.addEventListener('scroll', function() {
    if (window.pageYOffset > 300) {
        scrollTopBtn.classList.add('visible');
    } else {
        scrollTopBtn.classList.remove('visible');
    }
});

if (scrollTopBtn) {
    scrollTopBtn.addEventListener('click', function() {
        window.scrollTo({
            top: 0,
            behavior: 'smooth'
        });
    });
}

// ===== Active Nav Link on Scroll =====
const sections = document.querySelectorAll('.section, #homepage');
const navLinks = document.querySelectorAll('.nav-link');

window.addEventListener('scroll', function() {
    let current = '';
    const navHeight = document.querySelector('.navbar').offsetHeight;
    
    sections.forEach(section => {
        const sectionTop = section.offsetTop;
        const sectionHeight = section.clientHeight;
        
        if (window.pageYOffset >= (sectionTop - navHeight - 100)) {
            current = section.getAttribute('id');
        }
    });
    
    navLinks.forEach(link => {
        link.classList.remove('active');
        if (link.getAttribute('href') === '#' + current) {
            link.classList.add('active');
        }
    });
});

// ===== Contact Form Validation and Submission =====
const contactForm = document.getElementById('contactForm');

function showError(fieldId, errorId, message) {
    const field = document.getElementById(fieldId);
    const errorElement = document.getElementById(errorId);
    if (field && errorElement) {
        field.setAttribute('aria-invalid', 'true');
        errorElement.textContent = message;
        errorElement.classList.add('show');
    }
}

function clearError(fieldId, errorId) {
    const field = document.getElementById(fieldId);
    const errorElement = document.getElementById(errorId);
    if (field && errorElement) {
        field.setAttribute('aria-invalid', 'false');
        errorElement.textContent = '';
        errorElement.classList.remove('show');
    }
}

// Dynamic form validation based on HTML structure
function validateForm() {
    let isValid = true;
    
    // Get all required fields dynamically from the form
    const requiredFields = contactForm.querySelectorAll('[required]');
    
    requiredFields.forEach(field => {
        const fieldId = field.id;
        const errorId = fieldId + 'Error';
        const value = field.value.trim();
        const fieldType = field.type;
        const fieldName = field.name;
        
        // Clear previous error
        clearError(fieldId, errorId);
        
        // Check if field is empty
        if (!value) {
            const errorKey = `form.error.${fieldName || fieldId}`;
            const errorMessage = translations[currentLang] && translations[currentLang][errorKey] 
                ? translations[currentLang][errorKey]
                : `${field.getAttribute('data-i18n') ? translations[currentLang][field.getAttribute('data-i18n')] || field.name : field.name} is required`;
            showError(fieldId, errorId, errorMessage);
            isValid = false;
            return;
        }
        
        // Email validation
        if (fieldType === 'email') {
            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            if (!emailRegex.test(value)) {
                showError(fieldId, errorId, translations[currentLang]['form.error.emailInvalid'] || 'Please enter a valid email address');
                isValid = false;
            }
        }
        
        // Message/textarea validation (minimum length)
        if (field.tagName === 'TEXTAREA' && value.length < 10) {
            showError(fieldId, errorId, translations[currentLang]['form.error.messageShort'] || 'Message must be at least 10 characters');
            isValid = false;
        }
    });
    
    return isValid;
}

if (contactForm) {
    // Real-time validation - dynamically get all form fields
    const formFields = contactForm.querySelectorAll('input, textarea');
    formFields.forEach(field => {
        const fieldId = field.id;
        if (fieldId) {
            field.addEventListener('blur', function() {
                validateForm();
            });
            field.addEventListener('input', function() {
                const errorId = fieldId + 'Error';
                clearError(fieldId, errorId);
            });
        }
    });

    contactForm.addEventListener('submit', function(e) {
        e.preventDefault();
        
        if (!validateForm()) {
            // Focus on first error field
            const firstError = contactForm.querySelector('[aria-invalid="true"]');
            if (firstError) {
                firstError.focus();
            }
            return;
        }
        
        // Get form values dynamically
        const formData = new FormData(contactForm);
        const formValues = {};
        formData.forEach((value, key) => {
            formValues[key] = value.trim();
        });
        
        // Build email body dynamically from all form fields
        let emailBody = '';
        formFields.forEach(field => {
            if (field.name && formValues[field.name]) {
                const label = field.previousElementSibling?.textContent || field.name;
                emailBody += `${label}: ${formValues[field.name]}\n`;
            }
        });
        
        // Prepare email content
        const recipientEmail = document.querySelector('#contactEmailLink')?.href?.replace('mailto:', '') || 'ozcan@hacettepe.edu.tr';
        const name = `${formValues.firstName || ''} ${formValues.lastName || ''}`.trim() || 'Contact Form Submission';
        const subject = encodeURIComponent(`Contact Form - ${name}`);
        const body = encodeURIComponent(emailBody);
        
        // Create mailto link
        const mailtoLink = `mailto:${recipientEmail}?subject=${subject}&body=${body}`;
        
        // Open default mail application
        try {
            window.location.href = mailtoLink;
            
            // Reset form after a short delay
            setTimeout(function() {
                contactForm.reset();
                // Clear all errors dynamically
                formFields.forEach(field => {
                    if (field.id) {
                        clearError(field.id, field.id + 'Error');
                    }
                });
            }, 500);
        } catch (error) {
            console.error('Error opening mail client:', error);
            alert(translations[currentLang]['form.error.mailClient'] || 'Unable to open mail client. Please send an email manually to ' + recipientEmail);
        }
    });
}

// ===== Navbar Background on Scroll =====
const navbar = document.getElementById('navbar');

window.addEventListener('scroll', function() {
    if (window.scrollY > 50) {
        navbar.style.boxShadow = '0 4px 15px rgba(0, 0, 0, 0.15)';
    } else {
        navbar.style.boxShadow = '0 2px 10px rgba(0, 0, 0, 0.1)';
    }
});

// ===== Close Mobile Menu on Window Resize =====
window.addEventListener('resize', function() {
    if (window.innerWidth > 768) {
        navMenu.classList.remove('active');
        const spans = hamburger.querySelectorAll('span');
        spans[0].style.transform = 'none';
        spans[1].style.opacity = '1';
        spans[2].style.transform = 'none';
    }
});

